=== dalton/o-plan/source/xml-plans/plan.dtd
<!-- Copyright (c) Richard Tobin 1999.
     Richard Tobin has asserted the moral right to be identified as
     the author of this document.
     This document may be freely modified and redistributed provided 
     that this comment appears on every copy. -->

<!ELEMENT plan (node)+>
<!ATTLIST plan domain CDATA #IMPLIED
               task CDATA #IMPLIED>

<!ENTITY % node-type "(start|finish|action|dummy)">

<!ELEMENT node (pattern?,node-end,node-end)>
<!ATTLIST node name ID #REQUIRED
               parent IDREF #IMPLIED
               children IDREFS #IMPLIED
               type %node-type; #REQUIRED
	       min-duration CDATA #IMPLIED
               max-duration CDATA #IMPLIED>

<!ELEMENT pattern (#PCDATA)>

<!ENTITY % node-end "(begin|end)">

<!ELEMENT node-end (predecessors,successors)>
<!ATTLIST node-end end %node-end; #REQUIRED
                   est CDATA #IMPLIED
                   lst CDATA #IMPLIED>

<!ELEMENT predecessors (node-end-ref)*>

<!ELEMENT successors (node-end-ref)*>

<!ELEMENT node-end-ref EMPTY>
<!ATTLIST node-end-ref node IDREF #REQUIRED
                       end %node-end; #REQUIRED>

=== dalton/o-plan/source/xml-plans/get-to-work.xml
<!DOCTYPE plan SYSTEM "plan.dtd">

<?xml-stylesheet type="text/xsl" href="plan-to-html.xsl"?>

<plan domain="get-to-work" task="get_to_work_via_expansion">
   
   <node name="node-1" type="start">
      <pattern></pattern>
      <node-end end="begin" est="28800" lst="28800">
         <predecessors>
         </predecessors>
         <successors>
            <node-end-ref node="node-1" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="28800" lst="inf">
         <predecessors>
            <node-end-ref node="node-1" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3" end="begin"/>
         </successors>
      </node-end>
   </node>
   
   <node name="node-2" type="finish">
      <pattern></pattern>
      <node-end end="begin" est="30420" lst="inf">
         <predecessors>
            <node-end-ref node="node-3" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-2" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="30420" lst="inf">
         <predecessors>
            <node-end-ref node="node-2" end="begin"/>
         </predecessors>
         <successors>
         </successors>
      </node-end>
   </node>
   
   <node name="node-3" type="action">
      <pattern>(get_to_work self)</pattern>
      <node-end end="begin" est="28800" lst="inf">
         <predecessors>
            <node-end-ref node="node-1" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3" end="end"/>
            <node-end-ref node="node-3-1" end="begin"/>
         </successors>
      </node-end>
      <node-end end="end" est="30420" lst="inf">
         <predecessors>
            <node-end-ref node="node-3" end="begin"/>
            <node-end-ref node="node-3-4" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-2" end="begin"/>
         </successors>
      </node-end>
   </node>
   
   <node name="node-3-1" type="action">
      <pattern>(get_dressed)</pattern>
      <node-end end="begin" est="28800" lst="inf">
         <predecessors>
            <node-end-ref node="node-3" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3-1" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="29400" lst="inf">
         <predecessors>
            <node-end-ref node="node-3-1" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3-3" end="begin"/>
            <node-end-ref node="node-3-2" end="begin"/>
         </successors>
      </node-end>
   </node>
   
   <node name="node-3-2" type="action">
      <pattern>(read_paper)</pattern>
      <node-end end="begin" est="29400" lst="inf">
         <predecessors>
            <node-end-ref node="node-3-1" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3-2" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="29460" lst="inf">
         <predecessors>
            <node-end-ref node="node-3-2" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3-4" end="begin"/>
         </successors>
      </node-end>
   </node>
   
   <node name="node-3-3" type="action">
      <pattern>(eat_breakfast)</pattern>
      <node-end end="begin" est="29400" lst="inf">
         <predecessors>
            <node-end-ref node="node-3-1" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3-3" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="29520" lst="inf">
         <predecessors>
            <node-end-ref node="node-3-3" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3-4" end="begin"/>
         </successors>
      </node-end>
   </node>
   
   <node name="node-3-4" type="action">
      <pattern>(go_to work)</pattern>
      <node-end end="begin" est="29520" lst="inf">
         <predecessors>
            <node-end-ref node="node-3-3" end="end"/>
            <node-end-ref node="node-3-2" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3-4" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="30420" lst="inf">
         <predecessors>
            <node-end-ref node="node-3-4" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3" end="end"/>
         </successors>
      </node-end>
   </node>
   
</plan>

=== dalton/o-plan/source/xml-plans/get-to-work-level-1.xml
<!DOCTYPE plan SYSTEM "http://localhost/~jeff/oplan-xml/plan.dtd">

<plan domain="get-to-work" task="get_to_work_via_expansion">
   
   <node name="node-1" type="start">
      <pattern></pattern>
      <node-end end="begin" est="28800" lst="28800">
         <predecessors>
         </predecessors>
         <successors>
            <node-end-ref node="node-1" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="28800" lst="inf">
         <predecessors>
            <node-end-ref node="node-1" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3" end="begin"/>
         </successors>
      </node-end>
   </node>
   
   <node name="node-2" type="finish">
      <pattern></pattern>
      <node-end end="begin" est="30420" lst="inf">
         <predecessors>
            <node-end-ref node="node-3" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-2" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="30420" lst="inf">
         <predecessors>
            <node-end-ref node="node-2" end="begin"/>
         </predecessors>
         <successors>
         </successors>
      </node-end>
   </node>
   
   <node name="node-3" type="action">
      <pattern>(get_to_work self)</pattern>
      <node-end end="begin" est="28800" lst="inf">
         <predecessors>
            <node-end-ref node="node-1" end="end"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-3" end="end"/>
         </successors>
      </node-end>
      <node-end end="end" est="30420" lst="inf">
         <predecessors>
            <node-end-ref node="node-3" end="begin"/>
         </predecessors>
         <successors>
            <node-end-ref node="node-2" end="begin"/>
         </successors>
      </node-end>
   </node>
   
</plan>
